# both deployment and service will be here
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo-label
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo-label
# blueprint of each pod
  template:
    metadata:
      labels:
        app: mongo-label
# 1 matches 2
    spec:
      containers:
        - name: mongodb
          image: mongo:5.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERANAME
              valueFrom:
                secretKeyRef:
                  name: mongo-user
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-password
                  key: password
---

apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo-label
# 2 matches 1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 27017
# same as container port to which request is forwarded from service